apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default
  source:
    chart: tigera-operator
    repoURL: https://projectcalico.docs.tigera.io/charts
    targetRevision: v3.27.3
  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true