apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui-ingress
  namespace: velero
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: velero.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velero-ui-service
            port:
              number: 8080