apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui-ingress
  namespace: velero
  annotations:
    kubernetes.io/ingress.class: nginx
    # Προσθέτουμε και αυτό για σιγουριά
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: velero.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velero       # <--- ΑΛΛΑΓΗ: Από "velero-server" σε "velero"
            port:
              number: 8085     # <--- ΑΛΛΑΓΗ: Από "80" σε "8085"