apiVersion: v1
kind: Service
metadata:
  name: velero-ui-service
  namespace: velero
spec:
  selector:
    app: velero-ui # ΑΛΛΑΓΗ ΕΔΩ: Ψάχνει το νέο label του UI pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP