apiVersion: v1
kind: Service
metadata:
  name: velero-ui-service
  namespace: velero
spec:
  selector:
    app: velero-ui
  ports:
    - protocol: TCP
      port: 8080         
      targetPort: 3000   
  type: ClusterIP