apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui-ingress
  namespace: velero
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http: # ΑΦΑΙΡΕΣΑΜΕ ΤΟ HOSTNAME
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velero
            port:
              number: 8085