helm:
      values: |
        upgradeCRDs: false
        cleanUpCRDs: false
        
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: us-east-1
                s3ForcePathStyle: true
                s3Url: http://localstack-aws.localstack.svc.cluster.local:4566
          
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: us-east-1