apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: catalog-request-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: service_type
        value: "S3 Bucket"
        enum: 
          - "S3 Bucket"
          - "EC2 Instance"
      - name: environment
        value: "development"
        enum:
          - "development"
          - "staging"
          - "production"
      - name: resource_name
        value: "new-service"

  templates:
    - name: main
      dag:
        tasks:

          - name: call-s3-factory
            when: "{{workflow.parameters.service_type}} == 'S3 Bucket'"
            templateRef:
              name: infra-s3-factory
              template: provision-s3
            arguments:
              parameters:
                - name: bucket_name
                  value: "{{workflow.parameters.resource_name}}-{{workflow.parameters.environment}}"


          - name: call-ec2-factory
            when: "{{workflow.parameters.service_type}} == 'EC2 Instance'"
            templateRef:
              name: infra-ec2-factory
              template: provision-ec2
            arguments:
              parameters:
                - name: instance_name
                  value: "{{workflow.parameters.resource_name}}"
                - name: instance_type
                  value: "t3.micro"