apiVersion: v1
data:
  GITHUB_TOKEN: Z2l0aHViX3BhdF8xMUFLT0xCVkkwRVdpVU1OeEpLbVowX2JYRVVOS3NycW1vdE1WdGJkNEg5MGtxbGdaZ1hwYnBmRFhJUzVzNktBa0RGR0VaVVZDQ3ZDWVg1QkFh
kind: Secret
metadata:
  name: backstage-secrets
  namespace: default
