apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Λέμε στο Kustomize ποια είναι τα βασικά μας αρχεία
resources:
  - nginx.yaml
  - grafana-ingress.yaml
  - argocd-ingress.yaml

# Εδώ αρχίζει η μαγεία! 
# Θα προσθέσουμε αυτόματα ένα label σε ΟΛΑ μας τα resources, 
# χωρίς να πειράξουμε τα αρχικά YAML.
commonLabels:
  env: production
  managed-by: argocd

# Ας βάλουμε και ένα πρόθεμα (prefix) σε όλα τα ονόματα (pods, services, ingress)
namePrefix: prod-