apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce   # Μόνο ένα Pod μπορεί να γράφει κάθε φορά
  resources:
    requests:
      storage: 1Gi    # Ζητάμε 1 Gigabyte χώρο