apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
      - name: argo-server
        image: quay.io/argoproj/argocli:v3.5.0 
        args:
        - server
        - --auth-mode=server
        - --auth-mode=client
        ports:
        - containerPort: 2746
          name: https
        readinessProbe:
          httpGet:
            path: /
            port: 2746
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10