apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: provision-request-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: target_resource
        value: "s3" 
      - name: name
        value: "my-resource-name"

  templates:
    - name: main
      dag:
        tasks:
          - name: deploy-s3
            when: "{{workflow.parameters.target_resource}} == s3"
            templateRef:
              name: infra-s3-factory
              template: provision-s3
            arguments:
              parameters:
                - name: bucket_name
                  value: "{{workflow.parameters.name}}"
                - name: versioning
                  value: "Enabled"


          - name: deploy-ec2
            when: "{{workflow.parameters.target_resource}} == ec2"
            templateRef:
              name: infra-ec2-factory
              template: provision-ec2
            arguments:
              parameters:
                - name: instance_name
                  value: "{{workflow.parameters.name}}"
                - name: instance_type
                  value: "t3.micro"
                - name: volume_size
                  value: "20"