apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.0.0
    helm:
      skipSchemaValidation: true
      values: |
        backstage:
          image:
            registry: docker.io
            repository: nxcreed/my-backstage
            tag: v4
          appConfig:
            app:
              title: "Internal Developer Portal"
              baseUrl: http://backstage.local
            notifications:
                enabled: false
            backend:
              baseUrl: http://backstage.local
              cors:
                origin: http://backstage.local
              database:
                client: pg
                connection:
                  host: backstage-postgresql
                  port: 5432
                  user: postgres
                  # Αντλεί τον κωδικό από τη μεταβλητή περιβάλλοντος
                  password: ${POSTGRES_PASSWORD}
            integrations:
              github:
                - host: github.com
                  token: ${GITHUB_TOKEN}
          
          extraEnvVars:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: token
            # Φέρνουμε τον κωδικό της βάσης από το νέο Secret στο Backstage pod
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password

        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: "latest" # Ή όποιο tag βρήκες νωρίτερα
          auth:
            existingSecret: "backstage-db-auth"
            # ΑΥΤΟ ΕΙΝΑΙ ΤΟ ΚΛΕΙΔΙ: Λέμε στο Helm ποιο entry να κοιτάξει
            secretKeys: 
              userPasswordKey: "password"
              adminPasswordKey: "password"
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true