apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.0.0
    helm:
      skipSchemaValidation: true
      values: |
        backstage:
          image:
            registry: docker.io
            repository: nxcreed/my-backstage
            tag: v13
          
          extraInitContainers:
            - name: wait-for-postgres
              image: busybox:latest
              command: [ "sh", "-c", "until nc -zv backstage-postgresql 5432; do echo waiting for db; sleep 2; done;" ]

          appConfig:
            app:
              baseUrl: http://backstage.local
            
            backend:
              baseUrl: http://backstage.local
              cors:
                # ΔΕΧΟΜΑΣΤΕ ΚΑΙ ΤΑ ΔΥΟ ΓΙΑ ΝΑ ΜΗΝ ΣΚΑΕΙ Ο BROWSER
                origin: [ "http://backstage.local", "https://backstage.local" ]
                methods: [GET, POST, PUT, DELETE, OPTIONS]
                # ΟΛΑ ΤΑ HEADERS ΠΟΥ ΖΗΤΗΣΑΝ ΤΑ LOGS ΣΟΥ
                allowedHeaders: [Content-Type, Authorization, Cookie, X-Authorization, X-Requested-With]
                credentials: true
              
              database:
                client: pg
                connection:
                  host: backstage-postgresql
                  port: 5432
                  user: postgres
                  password: ${POSTGRES_PASSWORD}
                plugin:
                  default:
                    client: pg
              
              auth:
                keys:
                  - secret: ${BACKEND_SECRET}

            auth:
              environment: development
              providers:
                guest:
                  dangerouslyAllowQuietGuestAllowList: [ 'guest' ]
            
            signInPage: guest 

          extraEnvVars:
            - name: BACKEND_SECRET
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: BACKEND_SECRET
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: token
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password

        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: latest
          auth:
            existingSecret: "backstage-db-auth"
            secretKeys: 
              userPasswordKey: "password"
              adminPasswordKey: "password"

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true