apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.0.0
    helm:
      skipSchemaValidation: true
      values: |
        backstage:
          image:
            registry: docker.io
            repository: nxcreed/my-backstage # Το δικό σου custom image
            tag: v1                           # Το σωστό tag
          appConfig:
            app:
              baseUrl: http://backstage.local
            backend:
              baseUrl: http://backstage.local
              database:
                client: pg
                connection:                   # Η σύνδεση που έλειπε
                  host: backstage-postgresql
                  port: 5432
                  user: postgres
                  password: "backstage-password"
            integrations:
              github:
                - host: github.com
                  token: ${GITHUB_TOKEN}
          
          extraEnvVars:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: token

        postgresql:
          enabled: true
          image:                              # Προσθήκη για να λυθεί το ImagePullBackOff
            registry: docker.io
            repository: bitnami/postgresql
            tag: latest                         # Χρησιμοποιούμε σταθερό tag
          auth:
            postgresqlPassword: "backstage-password"
          primary:
            persistence:
              enabled: true
              size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true