apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
spec:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki-stack.monitoring.svc:3100
      access: proxy
      isDefault: false