apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 57.1.0
    helm:
      values: |
        alertmanager:
          enabled: false
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            podMonitorSelector: {}
            retention: 168h
            resources:
              limits:
                cpu: 500m
                memory: 1024Mi
              requests:
                cpu: 250m
                memory: 512Mi
        grafana:
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi         
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki-stack.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: 'Logs'
                type: file
                options:
                  path: /var/lib/grafana/dashboards/default
          dashboards:
            default:
              loki-logs:
                gnetId: 15155
                revision: 2
                datasource: Loki  
          # ------------------------------------------------------
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        nodeExporter:
          resources:
            limits:
              memory: 50Mi
            requests:
              memory: 20Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - SkipDryRunOnMissingResource=true