apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: apps

resources:
  - nginx.yaml
  - nginx-hpa.yaml
  - developer-rbac.yaml


commonLabels:
  env: production
  managed-by: argocd

namePrefix: prod-