apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dynamic-provision-nginx
  namespace: argo
spec:
  # Χρησιμοποιούμε το default service account που έχει τα RBAC δικαιώματα
  serviceAccountName: default 
  arguments:
    parameters:
    - name: app-name
      value: "dev-app-1"

  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: create-namespace
        template: make-ns
    - - name: deploy-argocd-app
        template: make-argo-app

  # Template 1: Δημιουργία Namespace
  - name: make-ns
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{workflow.parameters.app-name}}

  # Template 2: Δημιουργία ArgoCD Application
  - name: make-argo-app
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {{workflow.parameters.app-name}}
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: https://github.com/chrisignat/Platform-Engineer.git
            targetRevision: main
            path: apps/base/manifests
          destination:
            server: https://kubernetes.default.svc
            namespace: {{workflow.parameters.app-name}}
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
            - CreateNamespace=false # Το φτιάξαμε ήδη εμείς στο προηγούμενο step
            - NamespaceAutoPropagation=true
            - ApplyOutOfSyncOnly=true
            - RespectIgnoreDifferences=true