apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: golden-path-infrastructure-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: resource_type
        value: "s3"
      - name: resource_name
        value: "my-developer-bucket"
      - name: instance_type
        value: "t2.micro"

  templates:
    - name: main
      steps:
        - - name: tf-plan
            template: terraform-action
            arguments:
              parameters:
                - name: command
                  value: "plan"
        
        - - name: approve
            template: approve-step

        - - name: tf-apply
            template: terraform-action
            arguments:
              parameters:
                - name: command
                  value: "apply -auto-approve"

    - name: terraform-action
      inputs:
        parameters:
          - name: command
      container:
        image: hashicorp/terraform:latest
        command: [sh, -c]
        args:
          - |
            
            cat <<EOF > provider.tf
            provider "aws" {
              access_key                  = "test"
              secret_key                  = "test"
              region                      = "us-east-1"
              skip_credentials_validation = true
              skip_metadata_api_check     = true
              endpoints {
                s3 = "http://localstack:4566"
                ec2 = "http://localstack:4566"
              }
            }
            EOF

            if [ "{{workflow.parameters.resource_type}}" = "s3" ]; then
              echo 'resource "aws_s3_bucket" "b" { bucket = "{{workflow.parameters.resource_name}}" }' > main.tf
            else
              echo 'resource "aws_instance" "i" { ami = "ami-000000"; instance_type = "{{workflow.parameters.instance_type}}" }' > main.tf
            fi

            terraform init
            terraform {{inputs.parameters.command}}

    - name: approve-step
      suspend: {} # Αυτό δημιουργεί το "κουμπί" έγκρισης στο UI του Argo