apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 1.0.0
    helm:
      # Αυτό το flag παρακάμπτει το πρόβλημα με το "tls: failed to verify certificate"
      parameters:
        - name: "global.skipSchemaValidation"
          value: "true"
      values: |
        backstage:
          image:
            repository: backstageapp/backstage
            tag: latest
          extraEnvVars:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: GITHUB_TOKEN
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false # Παράκαμψη validation από την πλευρά του ArgoCD