apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: "1.0.0"
    helm:
      values: |
        backstage:
          image:
            repository: ghcr.io/NxCreed/backstage
            tag: latest
          # ΕΔΩ ΕΙΝΑΙ Η ΠΡΟΣΘΗΚΗ:
          imagePullSecrets:
            - name: ghcr-login-secret
          extraEnvVars:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-secrets
                  key: GITHUB_TOKEN
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true