apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack-aws
  namespace: argocd
spec:
  project: default
  source:
    chart: localstack
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: 0.6.14
    helm:
      values: |
        image:
          repository: localstack/localstack
          tag: latest
          pullPolicy: Always
        
        extraEnvVars:
          - name: LOCALSTACK_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: localstack-secrets
                key: auth-token
          - name: SERVICES
            value: "s3,sqs,lambda,rds,sns,dynamodb"
          - name: DEBUG
            value: "1"
          - name: LAMBDA_EXECUTOR
            value: "local"

        resources:
          requests:
            cpu: "200m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

        persistence:
          enabled: false  # Κράτα το false μέχρι να δούμε το "Green"

  destination:
    server: https://kubernetes.default.svc
    namespace: localstack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true