apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-redis-db
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.x.x
    # Πρόσθεσε αυτό το κομμάτι για να αλλάξεις το tag
    helm:
      values: |
        image:
          tag: 7.2.5-debian-12-r2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true