apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-redis-db
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami # <-- Δεν δείχνει στο repo σου, δείχνει στο public Helm repo της Bitnami!
    targetRevision: 18.x.x
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true