apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-redis-db
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.x.x
    helm:
      values: |
        image:
          registry: docker.io
          repository: library/redis
          tag: 7.2.4  # <--- Δοκίμασε το r16 ή απλά το "7.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true