name: Fix Port Scorecard
on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: 'Payload from Port'
        required: false
      port_context:
        description: 'Context from Port'
        required: false
      file_content: # ΠΡΟΣΘΕΣΕ ΑΥΤΟ ΕΔΩ
        description: 'The content from Port form'
        required: false

jobs:
  fix-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Custom File
        run: |
          echo "${{ github.event.inputs.file_content }}" > portal_note.txt
      - name: Commit and Push
        run: |
          git config --global user.name "Port-Bot"
          git config --global user.email "bot@getport.io"
          git add .
          git commit -m "docs: new file from portal with custom content"
          git push
