apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    chart: cost-analyzer
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 2.2.0
    helm:
      values: |
        kubecostProductConfigs:
          clusterName: my-lab-cluster
          # Σύνδεση με τον Prometheus στο monitoring namespace
          prometheusExternalUrl: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          prometheusMgmtApiEndpoint: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          
        prometheus:
          enabled: false
          fqdn: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
        
        grafana:
          enabled: false 


        networkCosts:
          enabled: true


        serviceMonitor:
          enabled: true
          additionalLabels:
            release: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true